# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        ('requests', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_price', models.PositiveIntegerField(verbose_name='مبلغ توافقی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغو شده')], db_index=True, default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='quotes.quote', verbose_name='پیشنهاد')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='requests.projectrequest', verbose_name='درخواست')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
