# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('requests', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('monthly_price', models.PositiveIntegerField(default=0)),
                ('lead_quota', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='FeaturedPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_placements', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'جایگاه ویژه',
                'verbose_name_plural': 'جایگاه\u200cهای ویژه',
                'db_table': 'featured_placements',
            },
        ),
        migrations.CreateModel(
            name='LeadPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purchases', to='requests.projectrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purchases', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'خرید لید',
                'verbose_name_plural': 'خریدهای لید',
                'db_table': 'lead_purchases',
            },
        ),
        migrations.CreateModel(
            name='PriceEstimateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price_per_sqm', models.PositiveIntegerField(default=0)),
                ('lighting_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('city_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_configs', to='catalog.service')),
            ],
            options={
                'verbose_name': 'پیکربندی تخمین قیمت',
                'verbose_name_plural': 'پیکربندی\u200cهای تخمین قیمت',
                'db_table': 'price_estimate_configs',
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'اشتراک تابلو\u200cساز',
                'verbose_name_plural': 'اشتراک\u200cهای تابلو\u200cساز',
                'db_table': 'vendor_subscriptions',
            },
        ),
    ]
