# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='محله')),
                ('business_type', models.CharField(blank=True, max_length=120, verbose_name='نوع کسب\u200cوکار')),
                ('width_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض (سانتی\u200cمتر)')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('material', models.CharField(blank=True, max_length=120, verbose_name='متریال')),
                ('lighting_type', models.CharField(blank=True, choices=[('none', 'بدون نور'), ('led', 'LED'), ('neon', 'نئون'), ('smd', 'SMD'), ('hidden', 'نور مخفی')], max_length=20, verbose_name='نورپردازی')),
                ('text_content', models.CharField(blank=True, max_length=300, verbose_name='متن تابلو')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل بودجه')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر بودجه')),
                ('installation_required', models.BooleanField(default=True, verbose_name='نیاز به نصب')),
                ('installation_height', models.CharField(blank=True, max_length=80, verbose_name='ارتفاع نصب')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='مهلت')),
                ('image', models.ImageField(blank=True, upload_to='requests/', verbose_name='عکس محل')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('reviewing', 'در حال بررسی'), ('receiving_quotes', 'دریافت پیشنهاد'), ('quoted', 'پیشنهاد دارد'), ('negotiating', 'در حال مذاکره'), ('accepted', 'پذیرفته\u200cشده'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=32)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_requests', to='locations.city', verbose_name='شهر')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_requests', to='vendors.vendor', verbose_name='تابلو\u200cساز ترجیحی')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_requests', to='catalog.service', verbose_name='نوع تابلو')),
            ],
            options={
                'verbose_name': 'درخواست پروژه',
                'verbose_name_plural': 'درخواست\u200cهای پروژه',
                'db_table': 'project_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='project_req_status_77bbd3_idx'), models.Index(fields=['city', 'service', 'status'], name='project_req_city_id_ec32b7_idx'), models.Index(fields=['customer', '-created_at'], name='project_req_custome_326ae9_idx')],
            },
        ),
    ]
