# Generated by Django 6.1.1 on 2026-09-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='requests/gallery/', verbose_name='تصویر')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='توضیح کوتاه')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requests.projectrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'عکس درخواست',
                'verbose_name_plural': 'عکس\u200cهای درخواست',
                'db_table': 'request_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
