# Generated by Django 6.1.1 on 2026-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='needs_guidance',
            field=models.BooleanField(default=False, help_text='مشتری نوع تابلو یا جزئیات فنی را نمی\u200cداند', verbose_name='نیاز به راهنمایی'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='size_choice',
            field=models.CharField(blank=True, help_text='small / medium / large / unsure', max_length=20, verbose_name='اندازه تقریبی'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='lighting_type',
            field=models.CharField(blank=True, choices=[('unsure', 'نمی\u200cدانم — تابلو\u200cساز پیشنهاد دهد'), ('none', 'بدون نور / فقط روز'), ('led', 'نور LED (رایج و کم\u200cمصرف)'), ('neon', 'نئون (جلوهٔ شبانه)'), ('smd', 'SMD'), ('hidden', 'نور مخفی')], max_length=20, verbose_name='نورپردازی'),
        ),
    ]
