# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(verbose_name='روز اجرا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('warranty', models.CharField(blank=True, max_length=120, verbose_name='گارانتی')),
                ('installation_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه نصب')),
                ('material_details', models.TextField(blank=True, verbose_name='جزئیات متریال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('viewed', 'مشاهده\u200cشده'), ('shortlisted', 'در لیست کوتاه'), ('accepted', 'پذیرفته\u200cشده'), ('rejected', 'رد شده'), ('expired', 'منقضی')], db_index=True, default='pending', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='requests.projectrequest', verbose_name='درخواست')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='vendors.vendor', verbose_name='تابلو\u200cساز')),
            ],
            options={
                'verbose_name': 'پیشنهاد قیمت',
                'verbose_name_plural': 'پیشنهادهای قیمت',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='quotes_vendor__6f8461_idx'), models.Index(fields=['request', 'status'], name='quotes_request_f5bf03_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'vendor'), name='unique_quote_per_vendor_request')],
            },
        ),
    ]
