# Generated by Django 6.1.1 on 2026-09-26 08:37

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200, verbose_name='نام کسب\u200cوکار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='آدرس')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='vendors/logos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='vendors/covers/')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('suspended', 'معلق')], db_index=True, default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('response_time_hours', models.PositiveIntegerField(default=24, help_text='میانگین زمان پاسخ به ساعت')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='locations.city', verbose_name='شهر')),
                ('services', models.ManyToManyField(blank=True, related_name='vendors', to='catalog.service', verbose_name='خدمات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تابلو\u200cساز',
                'verbose_name_plural': 'تابلو\u200cسازها',
                'db_table': 'vendors',
                'ordering': ['-is_featured', '-rating', 'business_name'],
                'indexes': [models.Index(fields=['verification_status', 'is_active'], name='vendors_verific_174b87_idx'), models.Index(fields=['city', 'is_active'], name='vendors_city_id_2397f5_idx')],
            },
        ),
    ]
