# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, upload_to='services/icons/', verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'db_table': 'services',
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='services_is_acti_3933a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CityServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, verbose_name='اسلاگ')),
                ('body', models.TextField(verbose_name='محتوا')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='متا')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pages', to='locations.city')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_pages', to='catalog.service')),
            ],
            options={
                'verbose_name': 'صفحه شهر/خدمت',
                'verbose_name_plural': 'صفحات شهر/خدمت',
                'db_table': 'city_service_pages',
                'unique_together': {('city', 'service')},
            },
        ),
    ]
