# Generated by Django 6.1.1 on 2026-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='لیست {"question": "...", "answer": "..."}', verbose_name='سوالات پرتکرار'),
        ),
        migrations.AddField(
            model_name='service',
            name='materials',
            field=models.TextField(blank=True, help_text='مواد و متریال\u200cهای متداول این خدمت', verbose_name='متریال رایج'),
        ),
        migrations.AddField(
            model_name='service',
            name='suitable_for',
            field=models.TextField(blank=True, help_text='کسب\u200cوکارهایی که این نوع تابلو برایشان مناسب است', verbose_name='مناسب برای'),
        ),
    ]
