# Generated by Django 6.1.1 on 2026-09-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/', verbose_name='تصویر')),
                ('is_published', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='locations.city')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='catalog.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='vendors.vendor', verbose_name='تابلو\u200cساز')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
                'db_table': 'portfolio_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_published'], name='portfolio_i_vendor__a457e8_idx'), models.Index(fields=['slug'], name='portfolio_i_slug_1ce330_idx')],
            },
        ),
    ]
