# Generated by Django 6.1.1 on 2026-09-28 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو'), ('aparat', 'ویدیوی آپارات')], default='image', max_length=10, verbose_name='نوع')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/gallery/', verbose_name='عکس')),
                ('video', models.FileField(blank=True, upload_to='portfolio/videos/', verbose_name='ویدیو')),
                ('poster', models.ImageField(blank=True, upload_to='portfolio/posters/', verbose_name='تصویر پیش\u200cنمایش ویدیو')),
                ('aparat_hash', models.CharField(blank=True, max_length=32, verbose_name='شناسه آپارات')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='توضیح کوتاه')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.portfolioitem', verbose_name='نمونه\u200cکار')),
            ],
            options={
                'verbose_name': 'رسانه نمونه\u200cکار',
                'verbose_name_plural': 'رسانه\u200cهای نمونه\u200cکار',
                'db_table': 'portfolio_media',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'image'), models.Q(('image', ''), _negated=True)), models.Q(('kind', 'video'), models.Q(('video', ''), _negated=True)), models.Q(('kind', 'aparat'), models.Q(('aparat_hash', ''), _negated=True)), _connector='OR'), name='portfolio_media_kind_has_source')],
            },
        ),
    ]
