# Generated by Django 6.1.1 on 2026-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('console', 'Console')], max_length=20)),
                ('recipient', models.CharField(max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'لاگ اعلان',
                'verbose_name_plural': 'لاگ\u200cهای اعلان',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
