# Generated by Django 6.1.1 on 2026-09-26 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], db_index=True, default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین پیام')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='quotes.quote', verbose_name='پیشنهاد')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'db_table': 'chat_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, upload_to='chat/', verbose_name='تصویر')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='خوانده\u200cشده در')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='گفتگو')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'), models.Index(fields=['conversation', 'read_at'], name='chat_messag_convers_5cba9b_idx')],
            },
        ),
    ]
